name: glacier-monitoring
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - numpy
  - matplotlib
  - xarray
  - netcdf4
  - cftime
  - pillow
  - requests
  - tk
  - pip
  - pip:
      - copernicusmarine
